services:
  postgres:
    image: postgres:17
    environment:
      - POSTGRES_USER=${PROJECT1_DB_USER:-airflow}
      - POSTGRES_PASSWORD=${PROJECT1_DB_PASSWORD:-airflow}
      - POSTGRES_DB=airflow
    ports:
      - "5433:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U airflow"]
      interval: 10s
      timeout: 5s
      retries: 5

  airflow-init:
    image: apache/airflow:3.1.7
    command: db migrate
    environment:
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql+psycopg2://${PROJECT1_DB_USER:-airflow}:${PROJECT1_DB_PASSWORD:-airflow}@postgres/airflow
      - AIRFLOW__CORE__FERNET_KEY=${AIRFLOW_FERNET_KEY}
    depends_on:
      postgres:
        condition: service_healthy

  airflow-webserver:
    image: apache/airflow:3.1.7
    command: api-server
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql+psycopg2://${PROJECT1_DB_USER:-airflow}:${PROJECT1_DB_PASSWORD:-airflow}@postgres/airflow
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
      - AIRFLOW__CORE__LOAD_EXAMPLES=False
      - AIRFLOW__CORE__TEST_CONNECTION=Enabled
      - AIRFLOW__CORE__FERNET_KEY=${AIRFLOW_FERNET_KEY}
      - AIRFLOW__API_AUTH__JWT_SECRET=${AIRFLOW_JWT_SECRET}
      - AIRFLOW_CONN_MY_POSTGRES_DB=postgresql://${PROJECT1_DB_USER:-airflow}:${PROJECT1_DB_PASSWORD:-airflow}@postgres/airflow
    volumes:
      - ./dags:/opt/airflow/dags
      - ./logs:/opt/airflow/logs
      - ./plugins:/opt/airflow/plugins
      - ./wfp_food_prices_ken.csv:/opt/airflow/data/wfp_food_prices_ken.csv
    ports:
      - "8080:8080"

  airflow-scheduler:
    image: apache/airflow:3.1.7
    command: scheduler
    depends_on:
      postgres:
        condition: service_healthy
      airflow-webserver:
        condition: service_started
    environment:
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql+psycopg2://${PROJECT1_DB_USER:-airflow}:${PROJECT1_DB_PASSWORD:-airflow}@postgres/airflow
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
      - AIRFLOW__CORE__TEST_CONNECTION=Enabled
      - AIRFLOW__CORE__FERNET_KEY=${AIRFLOW_FERNET_KEY}
      - AIRFLOW__API_AUTH__JWT_SECRET=${AIRFLOW_JWT_SECRET}
      - AIRFLOW__CORE__EXECUTION_API_SERVER_URL=http://airflow-webserver:8080/execution/
      - AIRFLOW_CONN_MY_POSTGRES_DB=postgresql://${PROJECT1_DB_USER:-airflow}:${PROJECT1_DB_PASSWORD:-airflow}@postgres/airflow
    volumes:
      - ./dags:/opt/airflow/dags
      - ./logs:/opt/airflow/logs
      - ./plugins:/opt/airflow/plugins
      - ./wfp_food_prices_ken.csv:/opt/airflow/data/wfp_food_prices_ken.csv

  airflow-dag-processor:
    image: apache/airflow:3.1.7
    command: dag-processor
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql+psycopg2://${PROJECT1_DB_USER:-airflow}:${PROJECT1_DB_PASSWORD:-airflow}@postgres/airflow
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
      - AIRFLOW__CORE__FERNET_KEY=${AIRFLOW_FERNET_KEY}
      - AIRFLOW_CONN_MY_POSTGRES_DB=postgresql://${PROJECT1_DB_USER:-airflow}:${PROJECT1_DB_PASSWORD:-airflow}@postgres/airflow
    volumes:
      - ./dags:/opt/airflow/dags
      - ./logs:/opt/airflow/logs
      - ./plugins:/opt/airflow/plugins
      - ./wfp_food_prices_ken.csv:/opt/airflow/data/wfp_food_prices_ken.csv

  airflow-triggerer:
    image: apache/airflow:3.1.7
    command: triggerer
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql+psycopg2://${PROJECT1_DB_USER:-airflow}:${PROJECT1_DB_PASSWORD:-airflow}@postgres/airflow
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
      - AIRFLOW__CORE__FERNET_KEY=${AIRFLOW_FERNET_KEY}
      - AIRFLOW_CONN_MY_POSTGRES_DB=postgresql://${PROJECT1_DB_USER:-airflow}:${PROJECT1_DB_PASSWORD:-airflow}@postgres/airflow
    volumes:
      - ./dags:/opt/airflow/dags
      - ./logs:/opt/airflow/logs
      - ./plugins:/opt/airflow/plugins
      - ./wfp_food_prices_ken.csv:/opt/airflow/data/wfp_food_prices_ken.csv