apiVersion: 1

datasources:
  - name: PostgreSQL - Food Prices
    type: postgres
    access: proxy
    url: postgres_project2:5432
    database: food_prices_kenya
    user: postgres
    secureJsonData:
      password: postgres
    jsonData:
      sslmode: disable
      postgresVersion: 1700
    isDefault: true
    editable: true
