name: 'food_prices_dbt'
version: '1.0.0'
config-version: 2

profile: 'food_prices_dbt'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - "target"
  - "dbt_packages"

vars:
  schema_name: "food_prices"
